version: "3"
services:
    dev:
      build: 
          context: .
          dockerfile: Dockerfile.dev
      ports:
          - "5200:5200"
      volumes:
            - /var/app/node_modules
            - .:/var/app
    test:
      build: 
          context: .
          dockerfile: Dockerfile.dev
      volumes:
            - /var/app/node_modules
            - .:/var/app
      command: ["ng","test"]
      
